name: SQLFluff

on:
  - push

jobs:
  publish-2-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: ","
          quotepath: false

      - name: Power BI Workspace Deploy
        uses: nathangiusti/Power-BI-Workspace-Deploy@v1.3
        with:
          files: ${{ steps.changed-files.outputs.all_modified_files }}
          separator: ","
          tenant_id: "570057f4-73ef-41c8-bcbb-08db2fc15c2b"
          config_file: ".github/config/workspace-deploy-config.yaml"
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}